name: "S-Charge to MQTT"
description: "Connects to an S-Charge compatible EV charger over websocket and publishes the data to Home Assistant over MQTT"
version: "1.0.0"
slug: "scharge"
init: false
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
startup: "application"
host_network: true

host_dbus: true
apparmor: true

homeassistant_api: true
hassio_api: true 

services:
  - mqtt:need

discovery:
  - mqtt

options:
  charger_serial_number: null
  websocket_receive_port: "auto"

schema:
  charger_serial_number: "str"
  websocket_receive_port: "str?"
